aralhibshi/calo-nutritionist-planner-be

backend/.env, backend/prisma/schema.prisma
- Initialize Prisma
- Implement Prisma Schema for all tables
=> feat: Prisma Init and Schema

frontend/src/index.tsx
=> amplify registration

backend/functions.ts, backend/package-lock.json, backend/package.json, backend/prisma/schema.prisma, backend/serverless.ts, backend/src/ingredients/createIngredient/handler.ts, backend/src/ingredients/serverless.yml, backend/src/libs/baseServerless.ts, backend/tsconfig.json
- Add Prisma package patterns
- Implement createIngredient Lambda to add user to DB using Prisma
- Implement createIngredient validation with response
- Implement createIngredient error handling with responses
=> feat: Create Ingredient and Prisma Package 

backend/src/ingredients/createIngredient/handler.ts, backend/src/ingredients/getIngredients/handler.ts, backend/src/ingredients/serverless.yml
- Refine the return structure and responses for the Create Ingredient endpoint to provide clearer success and error messages.
- Implement a new endpoint to retrieve a list of ingredients using the Get Ingredients functionality.
=> feat: Modify Create Ingredient Responses and Add Get Ingredients

backend/src/components/getComponents/handler.ts, backend/src/components/serverless.yml
=> feat: add getComponents

backend/src/components/searchComponents/handler.ts, backend/src/components/serverless.yml
=> feat: add search component

backend/src/components/createComponent/handler.ts, backend/src/components/getComponents/handler.ts, backend/src/components/searchComponents/handler.ts, backend/src/ingredients/deleteIngredient/handler.ts, backend/src/ingredients/searchIngredients/handler.ts, backend/src/ingredients/serverless.yml, backend/src/meals/createMeal/handler.ts, backend/src/meals/getMeal/handler.ts
- Implement Delete ingredient with proper validation and error handling
=> feat: Delete Ingredient

backend/src/components/createComponent/handler.ts, backend/src/components/serverless.yml
- Implement Request Parameters for Component Name in Lambda
- Implement string manipulation (upper case each first letter of word) for Name in searchComponent handler
- Implement string manipulation (upper case each first letter of word) for Name in createComponent handler
=> fix: Proper Search Component Handling

backend/src/components/deleteComponent/handler.ts, backend/src/components/serverless.yml
- Implement deleteComponent Lambda
- Implement deleteCOmponent Handler with proper returns/responses
- Modify deleteIngredient returns/response in Handler
=> feat: Delete Component

backend/src/components/createComponent/handler.ts, backend/src/meals/createMeal/handler.ts, backend/src/meals/searchMeals/handler.ts, backend/src/meals/serverless.yml
- Implement Request Parameter for Meal Name in searchMeal Lambda
- Implement string manipulation (upper case each first letter of word) for Name in createMeal handler
=> fix: Search Meal Lambda and Create Meal Name Casing

backend/src/components/createComponent/handler.ts, backend/src/meals/createMeal/handler.ts
- Add functionality to optionally include category and description in createComponent and createMeal
=> feat: Modify Create Component and Create Meal Handlers

backend/package-lock.json, backend/package.json, backend/src/components/createComponent/handler.ts, backend/src/libs/baseServerless.ts
- Implement serverless-offline plugin for offline testing
- Modify createComponent Handler to add multiple ingredients
=> feat: Create Component with Multiple Ingredients

backend/src/meals/createMeal/handler.ts
- Modify createMeal Handler to add multiple components to join table
=> feat: Create Meal with Multiple Components

src/libs/repositories/ingredientRepository.ts, src/services/ingredients/serverless.yml, src/services/ingredients/updateIngredient/handler.ts, src/services/ingredients/updateIngredient/useCase.ts
- Implement updateIngredient with validation and architecture
=> feat: Update Ingredient

prisma/migrations/20230824063550_ingredient_decimal/migration.sql, prisma/schema.prisma, src/libs/middleware/exceptionHandlerMiddleware.ts, src/libs/middleware/validationMiddleware.ts, src/services/ingredients/createIngredient/handler.ts, src/services/ingredients/createIngredient/useCase.ts, src/services/ingredients/deleteIngredient/handler.ts, src/services/ingredients/deleteIngredient/useCase.ts
- Modify ingredient decimals in Prisma Schema
- Create Prisma migration
- Modify validation middleware to include separate body and query validators
- Implement middlewares in deleteIngredient
=> feat: Prisma Schema and Delete Ingredient

package-lock.json, package.json, src/libs/interfaces/index.ts, src/libs/middleware/exceptionHandlerMiddleware.ts, src/libs/repositories/ingredientRepository.ts, src/services/ingredients/createIngredient/handler.ts, src/services/ingredients/createIngredient/useCase.ts, src/services/ingredients/deleteIngredient/handler.ts, src/services/ingredients/deleteIngredient/useCase.ts, src/services/ingredients/updateIngredient/handler.ts
- Implement deleteExceptionHandlerMiddleware
- Implement all middleware in deleteIngredient handler
- Modify IngredientRepository logs and method params
- Remove unnecessary try-catch in create and delete ingredient useCases
- Install http-errors type
=> feat: Delete Ingredient Middleware

src/libs/interfaces/index.ts, src/libs/prismaClient.ts, src/libs/repositories/componentRepository.ts, src/libs/repositories/ingredientRepository.ts, src/services/components/createComponent/handler.ts, src/services/components/createComponent/useCase.ts, src/services/components/deleteComponent/handler.ts, src/services/components/deleteComponent/useCase.ts, src/services/components/getComponents/handler.ts, src/services/components/searchComponents/handler.ts, src/services/components/serverless.yml, src/services/ingredients/createIngredient/handler.ts, src/services/ingredients/createIngredient/useCase.ts, src/services/ingredients/deleteIngredient/handler.ts, src/services/ingredients/deleteIngredient/useCase.ts, src/services/ingredients/getIngredients/handler.ts, src/services/ingredients/getIngredients/useCase.ts, src/services/ingredients/searchIngredients/handler.ts, src/services/ingredients/searchIngredients/useCase.ts, src/services/ingredients/serverless.yml, src/services/ingredients/updateIngredient/handler.ts, src/services/ingredients/updateIngredient/useCase.ts
- Implement singleton componentRepository instance for deleteComponent
- Initialize single Prisma Client file
- Implement single Prisma Client use in ingredient and compnent repos
- Implement all middleware for deleteComponent
- Remove unnecessary try-catch in deleteComponent useCase and Handler
=> feat: Singleton Repo for Delete Component & Single Prisma Client Instance

src/libs/repositories/ingredientRepository.ts, src/services/ingredients/updateIngredient/useCase.ts
- Remove capitalization on updateIngredient Id query
- Implement ingredient count in return of getIngredients repo method
=> hotifx: Improper Capitalization on Id & Ingredient Count

src/libs/interfaces/index.ts, src/libs/repositories/componentRepository.ts, src/libs/repositories/ingredientRepository.ts, src/services/components/getComponents/handler.ts, src/services/components/getComponents/useCase.ts, src/services/components/searchComponents/handler.ts, src/services/components/searchComponents/useCase.ts, src/services/components/serverless.yml, src/services/ingredients/searchIngredients/handler.ts, src/services/ingredients/searchIngredients/useCase.ts, src/services/ingredients/serverless.yml
- Implement count in getComponents repo method
- Implement count in searchIngredient repo method
- Implement request skip query in getComponents and searchComponents
- Implement query validation for getComponents and searchComponents
=> feat: Ingredient & Component Count, Skips, & Validation

src/libs/interfaces/index.ts, src/libs/repositories/ingredientRepository.ts, src/services/ingredients/getIngredients/handler.ts, src/services/ingredients/getIngredients/useCase.ts
- Implement take query for getIngredients
- Modify getIngredients query validation
=> feat: 'Take' Query for Get Ingredients

src/libs/middleware/exceptionHandlerMiddleware.ts, src/services/meals/serverless.yml
- Implement CORS in exception handling middleware
- Modify queries for getMeals & searchMeals
=> fix: CORS & Queries

src/libs/interfaces/index.ts, src/libs/repositories/componentRepository.ts, src/services/components/getComponents/handler.ts, src/services/components/getComponents/useCase.ts, src/services/components/serverless.yml
- Implement condition to get all components with ingredients in repo
=> feat: Get Components with Specific Ingredient

src/libs/repositories/componentRepository.ts
- Include components_ingredients in conditional getComponents
=> fix: ComponentsIngredients in Get Components

src/services/components/getComponents/useCase.ts, src/services/ingredients/getIngredients/useCase.ts, src/services/meals/getMeals/useCase.ts
- Capitialize name query in all get method useCases
=> fix: Get Method Search Name

src/libs/interfaces/index.ts, src/libs/repositories/mealRepository.ts, src/services/ingredients/updateIngredient/handler.ts, src/services/meals/getMeals/handler.ts, src/services/meals/getMeals/useCase.ts
- Implement condition to getMeals with provided ingredient_id
=> feat: Get Meals with Included Ingredient

src/libs/interfaces/index.ts, src/libs/repositories/ingredientRepository.ts, src/libs/repositories/mealRepository.ts, src/services/meals/serverless.yml, src/services/meals/updateMeal/handler.ts, src/services/meals/updateMeal/useCase.ts
- Implement temporary Meal Edit (improper implementation)
=> feat: Meal Edit (Temp)

src/services/components/getComponents/handler.ts, src/services/ingredients/getIngredients/handler.ts, src/services/meals/getMeals/handler.ts
- Modify minimum fetch amount in validation for all get handlers
=> fix: Minimum Fetch Amount

src/services/components/createComponent/handler.ts, src/services/components/updateComponent/handler.ts, src/services/ingredients/createIngredient/handler.ts, src/services/ingredients/updateIngredient/handler.ts
- Validate category options for create/update ingredients/components
=> feat: Valid Categories for Create/Update
